name: Pages (dev)

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages-dev"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cookiecutter
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          cache-version: 0
      - name: Build cookiecutter templates
        run: |
          mkdir -p downloads
          bash scripts/build-cookiecutters.sh
      - name: Build with Jekyll
        run: bundle exec jekyll build
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-dev
          path: _site
